//This file was generated by script mkregs.py

//register address mapping
#define FL_RESET 0
#define FL_DATAIN 1
#define FL_ADDRESS 2
#define FL_COMMAND 3
#define FL_COMMANDTP 4
#define FL_VALIDFLG 5
#define FL_READY 6
#define FL_DATAOUT 7
